version: '3.3'
services:
    jupyter:
        build:
            context: .
            dockerfile: deploy/jupyter.Dockerfile
        ports:
          - 4000:4000
        volumes:
          - .:/app
        command: "-m jupyter notebook . --ip=0.0.0.0 --port=4000 --allow-root --NotebookApp.token='' --NotebookApp.password=''"
    main:
        build:
            context: .
            dockerfile: deploy/main.Dockerfile
        ports:
          - 8081:8081
        command: -w 1 --bind 0.0.0.0:8081
    cache_redis:
        image: redis:latest
        restart: unless-stopped
